Error executing job with overrides: ['config=cpg0000_total_large.yaml']
Traceback (most recent call last):
  File "/home/icb/alessandro.palma/environment/IMPA/IMPA/scripts/../IMPA/main_hydra.py", line 57, in main
    datamodule = CellDataLoader(args)
  File "/home/icb/alessandro.palma/environment/IMPA/IMPA/IMPA/dataset/data_loader.py", line 242, in __init__
    self.init_dataset()
  File "/home/icb/alessandro.palma/environment/IMPA/IMPA/IMPA/dataset/data_loader.py", line 276, in init_dataset
    self.training_set, self.test_set = self.create_torch_datasets()
  File "/home/icb/alessandro.palma/environment/IMPA/IMPA/IMPA/dataset/data_loader.py", line 247, in create_torch_datasets
    dataset = CellDataset(self.args, device=self.device)
  File "/home/icb/alessandro.palma/environment/IMPA/IMPA/IMPA/dataset/data_loader.py", line 44, in __init__
    trt_dataset = self.fold_datasets['train'].loc[self.fold_datasets['train']["STATE"]=="trt"]
AttributeError: 'dict' object has no attribute 'loc'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Traceback (most recent call last):
  File "/home/icb/alessandro.palma/miniconda3/envs/IMPA_try/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/icb/alessandro.palma/miniconda3/envs/IMPA_try/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/icb/alessandro.palma/miniconda3/envs/IMPA_try/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/icb/alessandro.palma/miniconda3/envs/IMPA_try/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/icb/alessandro.palma/miniconda3/envs/IMPA_try/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/icb/alessandro.palma/environment/IMPA/IMPA/scripts/../IMPA/main_hydra.py", line 57, in main
    datamodule = CellDataLoader(args)
  File "/home/icb/alessandro.palma/environment/IMPA/IMPA/IMPA/dataset/data_loader.py", line 242, in __init__
    self.init_dataset()
  File "/home/icb/alessandro.palma/environment/IMPA/IMPA/IMPA/dataset/data_loader.py", line 276, in init_dataset
    self.training_set, self.test_set = self.create_torch_datasets()
  File "/home/icb/alessandro.palma/environment/IMPA/IMPA/IMPA/dataset/data_loader.py", line 247, in create_torch_datasets
    dataset = CellDataset(self.args, device=self.device)
  File "/home/icb/alessandro.palma/environment/IMPA/IMPA/IMPA/dataset/data_loader.py", line 44, in __init__
    trt_dataset = self.fold_datasets['train'].loc[self.fold_datasets['train']["STATE"]=="trt"]
AttributeError: 'dict' object has no attribute 'loc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/icb/alessandro.palma/environment/IMPA/IMPA/scripts/../IMPA/main_hydra.py", line 90, in <module>
    main()
  File "/home/icb/alessandro.palma/miniconda3/envs/IMPA_try/lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/icb/alessandro.palma/miniconda3/envs/IMPA_try/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/icb/alessandro.palma/miniconda3/envs/IMPA_try/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/icb/alessandro.palma/miniconda3/envs/IMPA_try/lib/python3.9/site-packages/hydra/_internal/utils.py", line 303, in run_and_report
    sys.exit(1)
SystemExit: 1
